export type Page =
  | 'dashboard'
  | 'manual'
  | 'overview'
  | 'codex'
  | 'github-copilot'
  | 'windsurf'
  | 'kiro'
  | 'cursor'
  | 'gemini'
  | 'codebuddy'
  | 'codex-instances'
  | 'instances'
  | 'accounts'
  | 'fingerprints'
  | 'wakeup'
  | 'verification'
  | 'settings';
